<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:uml="http://www.eclipse.org/uml2/3.0.0/UML" xmi:id="idModel" name="CircuitRC">
  <packagedElement xmi:type="uml:Package" xmi:id="idPackage" name="CircuitRC"/>
  <profileApplication xmi:type="uml:ProfileApplication" xmi:id="idProfileApplication">
    <eAnnotations xmi:type="ecore:EAnnotation" xmi:id="idProfileAnnotation" source="http://www.eclipse.org/uml2/2.0.0/UML">
      <references xmi:type="ecore:EPackage" href="pathmap://SysMLActivityExtensionsProfile.uml#ProfileContentId"/>
    </eAnnotations>
    <appliedProfile xmi:type="uml:Profile" href="pathmap://SysMLActivityExtensionsProfile.uml#ActivityProfileId"/>
  </profileApplication>
  <profileApplication xmi:type="uml:ProfileApplication" xmi:id="_zA1GsMznEeKH2rWo0wnQfw">
    <eAnnotations xmi:type="ecore:EAnnotation" xmi:id="_zA7NUMznEeKH2rWo0wnQfw" source="http://www.eclipse.org/uml2/2.0.0/UML">
      <references xmi:type="ecore:EPackage" href="http://www.femto-st.fr/disc/SysML4Modelica#/"/>
    </eAnnotations>
    <appliedProfile xmi:type="uml:Profile" href="pathmap://SysML4Modelica_PROFILES/SysML4Modelica.profile.uml#_XkGiwB07Ed-QQ4mYkrb7Gg"/>
  </profileApplication>
  <profileApplication xmi:type="uml:ProfileApplication" xmi:id="_zFHw0MznEeKH2rWo0wnQfw">
    <eAnnotations xmi:type="ecore:EAnnotation" xmi:id="_zFHw0cznEeKH2rWo0wnQfw" source="http://www.eclipse.org/uml2/2.0.0/UML">
      <references xmi:type="ecore:EPackage" href="http://www.femto-st.fr/disc/SysML4Modelica#//classes"/>
    </eAnnotations>
    <appliedProfile xmi:type="uml:Profile" href="pathmap://SysML4Modelica_PROFILES/SysML4Modelica.profile.uml#_Z9wxsMbPEeKThuE6BjWoqQ"/>
  </profileApplication>
  <profileApplication xmi:type="uml:ProfileApplication" xmi:id="_zIvskMznEeKH2rWo0wnQfw">
    <eAnnotations xmi:type="ecore:EAnnotation" xmi:id="_zIvskcznEeKH2rWo0wnQfw" source="http://www.eclipse.org/uml2/2.0.0/UML">
      <references xmi:type="ecore:EPackage" href="http://www.femto-st.fr/disc/SysML4Modelica#//types"/>
    </eAnnotations>
    <appliedProfile xmi:type="uml:Profile" href="pathmap://SysML4Modelica_PROFILES/SysML4Modelica.profile.uml#_l0KigMbQEeKThuE6BjWoqQ"/>
  </profileApplication>
  <profileApplication xmi:type="uml:ProfileApplication" xmi:id="_zMRhsMznEeKH2rWo0wnQfw">
    <eAnnotations xmi:type="ecore:EAnnotation" xmi:id="_zMRhscznEeKH2rWo0wnQfw" source="http://www.eclipse.org/uml2/2.0.0/UML">
      <references xmi:type="ecore:EPackage" href="http://www.femto-st.fr/disc/SysML4Modelica#//components"/>
    </eAnnotations>
    <appliedProfile xmi:type="uml:Profile" href="pathmap://SysML4Modelica_PROFILES/SysML4Modelica.profile.uml#_osBgcMbQEeKThuE6BjWoqQ"/>
  </profileApplication>
  <profileApplication xmi:type="uml:ProfileApplication" xmi:id="_zPzW0MznEeKH2rWo0wnQfw">
    <eAnnotations xmi:type="ecore:EAnnotation" xmi:id="_zPzW0cznEeKH2rWo0wnQfw" source="http://www.eclipse.org/uml2/2.0.0/UML">
      <references xmi:type="ecore:EPackage" href="http://www.femto-st.fr/disc/SysML4Modelica#//equationsandalgorithms"/>
    </eAnnotations>
    <appliedProfile xmi:type="uml:Profile" href="pathmap://SysML4Modelica_PROFILES/SysML4Modelica.profile.uml#_u4nlkMbQEeKThuE6BjWoqQ"/>
  </profileApplication>
  <profileApplication xmi:type="uml:ProfileApplication" xmi:id="_zTI-sMznEeKH2rWo0wnQfw">
    <eAnnotations xmi:type="ecore:EAnnotation" xmi:id="_zTI-scznEeKH2rWo0wnQfw" source="http://www.eclipse.org/uml2/2.0.0/UML">
      <references xmi:type="ecore:EPackage" href="http://www.femto-st.fr/disc/SysML4Modelica#//other"/>
    </eAnnotations>
    <appliedProfile xmi:type="uml:Profile" href="pathmap://SysML4Modelica_PROFILES/SysML4Modelica.profile.uml#_1LWu8MbQEeKThuE6BjWoqQ"/>
  </profileApplication>
</uml:Model>
